### PR TITLE
DDP-4221 refactor profile dob to single date

### PR DESCRIPTION
**Pull request by yufengwng**
Part 1 of [DDP-4221](https://broadinstitute.atlassian.net/browse/DDP-4221).

This PR merges the date-of-birth fields in user profile into a single birth date. These are only internal changes, the Profile APIs are kept the same.

Once we have this, it'll be easier to store participant's DoB in their profile and use it to calculate their "date-of-majority" that's used for the "age-up" process.

### CODE REVIEW

**Comment by yufengwng** [comment]
please run tests

**Comment by yufengwng** [comment]
please run tests

**Comment by yufengwng** [comment]
please run tests

**Review by ssettipalli — APPROVED** [review]
looks good to me

**Pull request merged**
