### PR TITLE
DDP-5402 - create indices for columns which used in WHERE clauses

### PR DESCRIPTION
**Pull request by evgeniipr**
## Context

It is found some fields which participate in WHERE clauses and are not indexed:
getEnrollmentStatusByUserAndStudyGuids: **user_study_enrollment.valid_to**
formActivityByGuidQuery: **revision.start_date, revision.end_date**
This could affect to the queries performance in **GetActivityInstanceRoute.java**.
Indices for these columns are created in this PR.

## Checklist

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [x] I have assessed potential risks and labeled using the `R-*` labels.
- [x] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [x] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [x] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [x] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

_If unsure or need help with any of the above items, add the `help wanted` label. For items that starts with `If applicable`, if it is not applicable, check it off and add `n/a` in front._

## FUD Score

_Overall, how are you feeling about these changes?_

- [x] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [ ] They are user-visible in dev as a regular user journey and require no additional instructions.
- [x] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [x] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [x] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

### CODE REVIEW

**Comment by yufengwng** [comment]
I'm curious if you have a sense of how much this helps with performance? E.g. maybe some numbers showing the response time of the GetActivityInstanceRoute call? Probably won't see a huge difference on local environment, but maybe setup a study locally, populate your local db with some users/data, and try a handful of requests to get a feel for performance before/after.

**Comment by evgeniipr** [comment]
> I'm curious if you have a sense of how much this helps with performance?

No, I haven't tested locally. I just followed the recommendation (regarding the performance) to index all fields used in WHERE. 
I thought may be to deploy it to prod and see how it helped. Anyway it shouldn't break anything.
But I'll try to create stress test locally - just interesting task)

**Review by MocanaAtBroad — DISMISSED** [review]

**Comment by MocanaAtBroad** [comment]
I don't expect big gains from these, but just good practice to ensure columns in WHERE clause are indexed.

**Review by MocanaAtBroad — APPROVED** [review]

**Comment by evgeniipr** [comment]
> I don't expect big gains from these, but just good practice to ensure columns in WHERE clause are indexed.

I agree that in the existing of user_study_enrollment.valid_to will not help much - this is only 1 query called in GetActivityInstanceRoute where it is used, but regarding revision.start_date, revision.end_date - it used in quite many SQL queries and not only in the cached ones. So it should improve performance at least a little.

**Pull request merged**
