### PR TITLE
Refactor query for fetching whole answer objects

### PR DESCRIPTION
**Pull request by yufengwng**
We have a query that builds the different types of answers in one go. I pulled it out of `ActivityInstanceDao` and into `AnswerDao`. I did this to support some changes we need to make for DDP-4278, which I'll do in a separate PR.

### CODE REVIEW

**Comment by yufengwng** [comment]
please run tests

**Comment by yufengwng** [comment]
please run tests

**Review by spookymotion — APPROVED** [review]
LGTM

**Comment by yufengwng** [comment]
please run tests

**Pull request merged**
