### PR TITLE
DDP-5675 Add First Name to User's profile

### PR DESCRIPTION
**Pull request by YuriyPavlovBI**

### CODE REVIEW

**Comment by charlottedye** [comment]
This looks good to me but would you mind linking me to the ticket so I can double check?  Thanks

**Comment by YuriyPavlovBI** [comment]
> This looks good to me but would you mind linking me to the ticket so I can double check? Thanks

https://broadinstitute.atlassian.net/browse/DDP-5675

**Comment by charlottedye** [comment]
I think we should probably review this with Jeff that this is what we want.  I actually find the ticket description for this confusing (what does he mean by adding them to ElasticSearch specifically?) so let's make sure we are on the same page.

**Comment by YuriyPavlovBI** [comment]
> I think we should probably review this with Jeff that this is what we want. I actually find the ticket description for this confusing (what does he mean by adding them to ElasticSearch specifically?) so let's make sure we are on the same page.

The problem was that firstName and lastName in profile were always null.

**Review by charlottedye — APPROVED** [review]

**Comment by charlottedye** [comment]
The commit log is broken, though

**Comment by YuriyPavlovBI** [comment]
> The commit log is broken, though

This was merged together with another PR

**Pull request closed without merging**
