### PR TITLE
Update pull request template to be more checklist-oriented

### PR DESCRIPTION
**Pull request by yufengwng**
## Context

New conventions for PR!

1. Template is now more "checklist-oriented". Instead of choosing items from a category, you'll add labels and tick off items like a todo list.
2. Labels are grouped by category, e.g. risk labels start with `R-` and infosec labels start with `I-`.
3. Add as many or as little labels as you want.

## Checklist

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [x] I have assessed potential risks and labeled using the `R-*` labels.
- [x] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [x] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [x] (n/a) If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [x] (n/a) If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

_If unsure or need help with any of the above items, add the `help wanted` label. For items that starts with `If applicable`, if it is not applicable, check it off and add `n/a` in front._

## FUD Score

_Overall, how are you feeling about these changes?_

- [x] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [ ] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [ ] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [ ] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

### CODE REVIEW

**Comment by yufengwng** [comment]
Checkout the labels here: https://github.com/broadinstitute/ddp-study-server/labels
CC @ssettipalli @raiks2 @MocanaAtBroad @fat23cat @bskinner

**Comment by zyme** [comment]
Looks good to me!

**Comment by bskinner** [comment]
I have concerns about the current PR template and label setup significantly decreasing the SNR of the pull requests tab, and increasing the difficulty of both opening and managing active PRs. The ticket references, and the repetition of information present in the tickets, and information overload from the sheer number of potential labels make it difficult to parse out what is actually going on.

**Comment by yufengwng** [comment]
@bskinner thanks for the note!

For opening PRs, can you elaborate how this is more difficult than previous setup? We're doing roughly the same amount of work. But instead of checking boxes in PR description, we're adding labels.

For managing active PRs, I personally not sure what the difficulties are. Maybe you have more experiences here to share?

I'm not quite catching the note about information overload. Are we comparing the ticket descriptions with the PR "context"? Yeah they can sometimes say the same thing, but other times they might have different information (e.g. ticket says "...add a new flag", and PR says "...i implemented flag as a boolean"). And I will say that labels can help us out with overload, since they can be viewed as the TL;DR or a ticket. Are there anything specific about the PR template/labels we can change to help in this regard?

And in general, any thoughts in getting more signal and less noise?

**Comment by zyme** [comment]
@yufengwng thanks for pulling this together.  While pondering the next steps on our SDLC, I find myself wondering if many of the things in the first checkbox list should go into the ticket at the time it's created.  I think we'd benefit from moving some of these thoughts to earlier in the process, perhaps mandating some kind of taggery in the tickets.

I think the changes here are an improvement on the checklist we currently have, so I'm all for trying them out.  What would folks say to merging this up and adding a process meeting topic for what should go into ticket custom fields/labels and what should stay in PR checklist?

**Comment by bskinner** [comment]
That seems like a reasonable approach- push it onto the stack for the process meeting?

> @yufengwng thanks for pulling this together. While pondering the next steps on our SDLC, I find myself wondering if many of the things in the first checkbox list should go into the ticket at the time it's created. I think we'd benefit from moving some of these thoughts to earlier in the process, perhaps mandating some kind of taggery in the tickets.
> 
> I think the changes here are an improvement on the checklist we currently have, so I'm all for trying them out. What would folks say to merging this up and adding a process meeting topic for what should go into ticket custom fields/labels and what should stay in PR checklist?

**Comment by yufengwng** [comment]
please run tests

**Review by bskinner — APPROVED** [review]
Let's get this in, and tweak from there!

**Comment by yufengwng** [comment]
Okie dokie! (please run tests)

**Pull request merged**
