### PR TITLE
DDP-5681: Require email verification

### PR DESCRIPTION
**Pull request by aleksey-kuznetsov**
## Context

_Say a few words about the bigger picture beyond this PR. How do your changes improve life for our users? Link directly to the jira ticket (just type "DDP-..." and it'll automatically link) to help your teammates quickly get up to speed on the motivation for these changes._

Introduced new rule for Auth0 that forces email verification that can be included in other tenant's configuration files.

## Checklist

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [ ] I have assessed potential risks and labeled using the `R-*` labels.
- [ ] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [x] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [x] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [ ] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

_If unsure or need help with any of the above items, add the `help wanted` label. For items that starts with `If applicable`, if it is not applicable, check it off and add `n/a` in front._

## FUD Score

_Overall, how are you feeling about these changes?_

- [x] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

Updated `tenant.yml` for RGP is already deployed to `dev`, although email verification is disabled until all necessary changes (both frontend and backend) are merged. For testing purposes go to Auth0 -> Rules and enable `Force email verification` rule.

- [ ] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [x] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [ ] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

### CODE REVIEW

**Review by charlottedye — COMMENTED** [review]
This is a little weird because it doesn't seem to actually prevent login.  When I tested this, if you tried to log in before verifying your email, you did get sent to an error page, but if you then verified the email, you were already logged in.  It seems like we should prevent login altogether unless the email is verified.

**Comment by aleksey-kuznetsov** [comment]
@charlottedye I'm not exactly sure what you've experienced but have you tried it with changes from a PR for the frontend? I'm talking about [this](https://github.com/broadinstitute/ddp-angular/pull/474).

Unfortunately, we have to also make changes to the existing `Auth0CodeCallbackComponent` and `LoginLandingComponent` on the frontend side to make it work.

**Comment by aleksey-kuznetsov** [comment]
@charlottedye can you try it once again from the branch I've sent you in the previous comment? Besides, don't forget to enable associated rule in the Auth0 dashboard for RGP tenant.

**Review by charlottedye — APPROVED** [review]
See frontend ticket review

**Pull request merged**
