### PR TITLE
DDP-5588 rgp: embedded nested activities for family members

### PR DESCRIPTION
**Pull request by yufengwng**
## Context

Instead of `COMPOSITE` questions, we'll use embedded `ACTIVITY` blocks and child activities to represent the set of questions about family members. There's some UI bugs and styling to fix, but this PR should be enough to get us going.

## Checklist

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [x] I have assessed potential risks and labeled using the `R-*` labels.
- [x] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [x] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.

## FUD Score

- [x] :relaxed: All good, business as usual!

## How do we demo these changes?

- [x] Getting dev into a state where this is user-visible requires some tech fiddling.
    - Need to redeploy RGP study in `dev` environment.

## Testing

- [x] I have written zero automated tests but have poked around locally to verify proper functionality

### CODE REVIEW

**Comment by yufengwng** [comment]
This is ready for review!

**Review by charlottedye — CHANGES_REQUESTED** [review]
It's possible these are build issues or something on my end, but here's what I noticed:
-The "add another" buttons look like there is overlapping text and I don't see remove buttons
-If there are two siblings, for example, it's a little hard to tell where one ends and the next beings
-If they answer yes to the question about whether the relative has the same condition, the question about age of onset doesn't appear.  Similar with is parent available to participate and deceased-related questions

**Comment by yufengwng** [comment]
Nope, these are not build issues! These are Angular UI issues that I briefly mentioned -- these are being worked on now. And the "add button": that one needs some styling touch up.

**Review by charlottedye — DISMISSED** [review]

**Review by charlottedye — APPROVED** [review]
Didn't realize this wasn't marked as approved...

**Pull request merged**
