### PR TITLE
[DSS] DDP-8000: Drop auth0_domain column from the client table

### PR DESCRIPTION
**Pull request by Trimax**

### CODE REVIEW

**Comment by bskinner** [comment]
Have you verified that the `/pepper/v1/temporary-users` endpoint works properly, with this fix, on a database that has not had tests run against it?

**Comment by Trimax** [comment]
> 

Снимок экрана 2022-05-11 в 15 16 23

**Comment by bskinner** [comment]
> > 
> 
> Снимок экрана 2022-05-11 в 15 16 23

Please re-read my comment. That looks very much like tests have been run against that database.

**Review by bskinner — APPROVED** [review]
Resolved the outstanding conversations in a separate channel. I'm good with merging this.

**Pull request merged**
