### PR TITLE
Add access_roles display text

### PR DESCRIPTION
**Pull request by denniscunningham**
PEPPER-972

Add DSM access role display text that describes each role in DSM, for use with user administration UI. This [sheet](https://docs.google.com/spreadsheets/d/1ucUQw5QfOCcITiZVIgknfgZqGA8IY3GqGq3B-IDqoJ8/edit#gid=1472255211) was used as a source.

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [x] I have assessed potential risks and labeled using the `R-*` labels.
- [x] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [ ] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [ ] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [ ] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

_If unsure or need help with any of the above items, add the `help wanted` label. For items that starts with `If applicable`, if it is not applicable, check it off and add `n/a` in front._

## FUD Score

_Overall, how are you feeling about these changes?_

- [x] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [x] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [ ] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [x] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

### CODE REVIEW

**Review by JeffKorte — COMMENTED** [review]
@denniscunningham, I just added the UI label for mr_no_request_tissue to the tracking spreadsheet, so that needs to be added.

Also, will these appear in alpha order in the UI?

**Comment by denniscunningham** [comment]
@JeffKorte Happy to make that change,  but perhaps let's coordinate with Pegah first. If CMI thinks that role does something, but DSM has not implemented it, there is a disconnect.
Re: Order of display in UI... how do you want them arranged in the UI? For CMI we will have 20+ roles. Giorgi and I can workout how to arrange and order them once we know your preference.

**Comment by JeffKorte** [comment]
Thanks @denniscunningham!  Can they please be arranged alphabetically first by the main functional area (for example, "Kit" would appear before "Medical Records") and then by the secondary function (for example "Kit - Receive and scan" would come before "Kit - Shipping")?  Does that make sense?

**Review by ssettipalli — APPROVED** [review]

**Comment by pegahtah** [comment]
Sorry I am too late to this. @denniscunningham the mr_no_request_tissue is implemented to change the user's abilities to download in frontend ( will stop displaying the download button for Tissue requests)

**Pull request merged**
