### PR TITLE
DDP-7343-update-ddp-automation-log4j-version

### PR DESCRIPTION
**Pull request by Rinchan20**
security update just in case, I don't explicitly use log4j but it seems a dependency does, posting result of dependency tree:

```
mvn dependency:tree | grep log4j
[INFO] |  |  \- org.slf4j:slf4j-log4j12:jar:2.0.0-alpha5:compile
[INFO] |  +- log4j:log4j:jar:1.2.16:compile
[INFO]    |  |  +- org.apache.logging.log4j:log4j-api:jar:2.15.0:compile
```

### CODE REVIEW

**Comment by Rinchan20** [comment]
tests are a bit old (but on way to being updated in a different branch)...import line taken out since class was changed since then (I think changed from JdbiAnswer to JdbiCompositeAnswer)

**Review by bskinner — DISMISSED** [review]
Looks good to me

**Review by MocanaAtBroad — DISMISSED** [review]

**Comment by Rinchan20** [comment]
```
mvn dependency:tree | grep log4j
[INFO] |  |  \- org.slf4j:slf4j-log4j12:jar:2.0.0-alpha5:compile
[INFO] |  +- log4j:log4j:jar:1.2.16:compile
[INFO]    |  |  +- org.apache.logging.log4j:log4j-api:jar:2.16.0:compile
```

**Review by bskinner — APPROVED** [review]
👍

**Pull request merged**
