### PR TITLE
DDP-1855 allow multiple templates for notification action

### PR DESCRIPTION
**Pull request by yufengwng**
## Context

Allow studies to configure multiple email templates for an email notification event action, so that we can sent out email in a different language. When we build the email message in Housekeeping, we will determine the appropriate email to use based on user's preferred language and study's supported languages.

The database migration script will take care of migrating existing study configurations to this new schema, so no additional intervention needed. Study-builder is also updated to support the old format of a single email template, so old config files do not need to be updated.

## Checklist

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [x] I have assessed potential risks and labeled using the `R-*` labels.
- [x] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [x] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.

## FUD Score

_Overall, how are you feeling about these changes?_

- [x] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [x] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [x] I have written automated positive tests
- [ ] I have written automated negative tests
- [x] I have tried existing studies locally and emails seem to work
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [x] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

### CODE REVIEW

**Review by charlottedye — DISMISSED** [review]
This looks good to me, assuming that there's a ticket somewhere to note that there is still remaining work to use the study's default language for templates if a user hasn't specified a language rather than just the first language listed.  Also might be worth adding a note about that in the pull request and/or ticket.  Looks good otherwise, though.

**Comment by yufengwng** [comment]
@charlottedye I already took care of that in PR #243 :)

**Comment by charlottedye** [comment]
Nice!

**Review by ssettipalli — APPROVED** [review]
looks ok to me.
We should start looking into using dynamic templates rather than replicating a template for each supported language.

**Pull request merged**
