### PR TITLE
Fix temp-user cleanup job to cleanup queue/sync data

### PR DESCRIPTION
**Pull request by yufengwng**
Noticed an alert from `test` channel:
```
Error while executing job 'cleanup.temp-user'  Cannot delete or update a parent row: a foreign key constraint fails (peppertest.queued_event, CONSTRAINT queued_event_operator_user_fk FOREIGN KEY (operator_user_id) REFERENCES user (user_id))
```

It looks like we're queuing up events for temp users, so we need to clean those up when removing expired temp users. Also cleaning up data-sync requests as well.

### CODE REVIEW

**Comment by yufengwng** [comment]
please run tests

**Review by ssettipalli — APPROVED** [review]
looks good to me

**Comment by yufengwng** [comment]
please run tests

**Review by raiks2 — APPROVED** [review]
LGTM

**Pull request merged**
