### PR TITLE
DDP-8554. Border fixes

### PR DESCRIPTION
**Pull request by Trimax**

### CODE REVIEW

**Review by bskinner — COMMENTED** [review]
Does this patch successfully apply against an install which has already had the previous version run?

**Comment by MocanaAtBroad** [comment]
@bskinner I am pretty sure this is a modification to @Trimax's previous patch. Has been freakin' tricky to get this right!

**Comment by MocanaAtBroad** [comment]
@Trimax Left you comment on my own PR. Would welcome suggested changes (or a PR on my PR) that would add the same checks you have been doing for AOM to the new medical release v2.
https://github.com/broadinstitute/ddp-study-server/pull/2256

**Review by MocanaAtBroad — APPROVED** [review]

**Comment by Trimax** [comment]
> Does this patch successfully apply against an install which has already had the previous version run?

Yep, it is.

**Pull request merged**
