### PR TITLE
DDP-5442-investigate-auth0-log-events: add POST ../auth-0log-event en…

### PR DESCRIPTION
**Pull request by evgeniipr**
…dpoint which logs posted log event data (in order to check possible data content)

## Context

This is preliminary code implementing REST endpoint: POST ../pepper/v1/auth0-log-event which does nothing except that it logs the auth0 log event data passed from auth0 (this URL should be specified during auth0 stream custom webhook creation).
We can configure custom webhook with this URL (and deploy this endpoint to dev env) and check from logs which kind of payload data passed from auth0 (basing on this we can design DB table for storing auth0 log data).

## Checklist

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [x] I have assessed potential risks and labeled using the `R-*` labels.
- [x] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [x] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [x] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [x] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

## FUD Score

_Overall, how are you feeling about these changes?_

- [x] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

It needs to deploy this change to dev env, specify URL ../pepper/v1/auth0-log-event during auth0 custom webhook creation: https://manage.auth0.com/dashboard/us/ddp-dev/log-streams/create
And then analyze the log contents (finding INFO log messages started with "AUTH0-LOG-EVENT") checking which fields the POST body contains.

- [x] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [x] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [ ] These changes require no special release procedures--just code!
- [x] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

About release changes: after deploying the code to dev env it needs to create Auth0 Stream Custom Webhook: https://manage.auth0.com/dashboard/us/ddp-dev/log-streams/create
where to specify URL ../auth0-log-event.

### CODE REVIEW

**Review by yufengwng — DISMISSED** [review]

**Review by zyme — COMMENTED** [review]
Looks good to me for a temporary way to figure out what our real payloads look like.  Can you add the `whitelist(..., cfg.getStringList(ConfigFile.AUTH0_IP_WHITE_LIST));` to this route, similar to how `API.REGISTRATION` is protected in `DataDonationPlatform`?

**Comment by evgeniipr** [comment]
> Looks good to me for a temporary way to figure out what our real payloads look like. Can you add the `whitelist(..., cfg.getStringList(ConfigFile.AUTH0_IP_WHITE_LIST));` to this route, similar to how `API.REGISTRATION` is protected in `DataDonationPlatform`?

Hi! Added, pushed.

**Comment by yufengwng** [comment]
Looks like this is replaced by #592. Let's close this PR.

**Comment by evgeniipr** [comment]
The PR closed as no needed - investigation completed. A new PR created for this feature: DDP-5442-auth0-log-events

**Pull request closed without merging**
