### PR TITLE
Order events consistently when processing

### PR DESCRIPTION
**Pull request by yufengwng**
Added `order by` clause to queries use to fetch events so we have a consistent ordering.

### CODE REVIEW

**Comment by yufengwng** [comment]
please run tests

**Comment by yufengwng** [comment]
So far from my testing, it doesn't seem to cause issues for osteo or the age-up events, but we should respect ordering nonetheless.

**Comment by yufengwng** [comment]
please run tests

**Comment by yufengwng** [comment]
please run tests

**Review by spookymotion — APPROVED** [review]

**Pull request merged**
