### PR TITLE
DDP-7117 | update mapping file for dsm

### PR DESCRIPTION
**Pull request by ScalaChamp**
## Context

There was a need to update the `participants_structured.json` due to the following requirements:

1) DSM data migration from mysql server to ES;
2) Writing/Updating DSM data to ES.

Updating `participants_structured.json` was an integral part of this feature since we needed a way of representing different kind of objects and their relationships with other objects.

We used appropriate data types where possible and the combination of `text` & `keyword` in all other cases in order to maximize the searchability (exact, non-exact) and sorting.

## Checklist

- [ ] I have labeled the type of changes involved using the `C-*` labels.
- [ ] I have assessed potential risks and labeled using the `R-*` labels.
- [ ] I have considered error handling and alerts, and added `L-*` labels as needed.
- [ ] I have considered security and privacy, and added `I-*` labels as needed
- [ ] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [ ] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [ ] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

_If unsure or need help with any of the above items, add the `help wanted` label. For items that starts with `If applicable`, if it is not applicable, check it off and add `n/a` in front._

## FUD Score

_Overall, how are you feeling about these changes?_

- [ ] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [ ] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [ ] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [ ] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

### CODE REVIEW

**Comment by ssettipalli** [comment]
@Anzori-Ghurtchumelia 
Can you please add some description (PR context) on why we need these changes and also mention related tickets 
Are these mapping changes mainly needed for data export to elastic from DSS or data export/elastic data updates from DSS ?

**Comment by ScalaChamp** [comment]
@ssettipalli @SimoneMaiwald

Hey guys, since me and @gmakharat almost finished with this feature/made all the necessary changes to ES mappings we converted back this PR from `draft` to `ready-to-review` one, please make a review and we'll be able to merge it.

@Anzori-Ghurtchumelia :
All these mapping changes are needed to export DSM data (and not DSS data) to participants_structured index ?

**Review by gmakharat — DISMISSED** [review]

**Review by ssettipalli — COMMENTED** [review]
Guram:
All these mapping changes needed to export DSM data to participants_structured index ?

**Comment by SimoneMaiwald** [comment]
> Guram: All these mapping changes needed to export DSM data to participants_structured index ?

yes

**Review by gmakharat — APPROVED** [review]

**Comment by ScalaChamp** [comment]
@ssettipalli @SimoneMaiwald 

I believe this is the final version of ES mappings, we can merge that to `develop` that would also make for us easier to upload new indices straight from `develop` branch.

**Pull request merged**
