### PR TITLE
DDP-6859 Spanish Translation of the Application Form (Tell Us Your St…

### PR DESCRIPTION
**Pull request by YuriyPavlovBI**
Here's what changed:

Spanish phrases were added (es.conf) - it is going to be applied using UpdateTemplatesInPlace task which was improved to work with nested activities as well and also to update missing parts like confirmPlaceholderTemplate, addButtonTemplate, activity status summaries
ES language was added to the study config (study.conf) - it is going to be applied using UpdateStudyLanguages task

### CODE REVIEW

**Comment by aleksey-kuznetsov** [comment]
Let's wait before merging this, there are a couple of bags in the language update script.

**Comment by MocanaAtBroad** [comment]
Please update ticket to tell us what you are trying to do. I can see you want to add  want to add Spanish translations. Please walk us through changes.

**Comment by YuriyPavlovBI** [comment]
> Please update ticket to tell us what you are trying to do. I can see you want to add want to add Spanish translations. Please walk us through changes.

Here's what changed:
1. Spanish phrases were added (es.conf) - it is going to be applied using UpdateTemplatesInPlace task which was improved to work with nested activities as well and also to update missing parts like confirmPlaceholderTemplate, addButtonTemplate, activity status summaries
2. ES language was added to the study config (study.conf) - it is going to be applied using UpdateStudyLanguages task

**Comment by YuriyPavlovBI** [comment]
> Please update ticket to tell us what you are trying to do. I can see you want to add want to add Spanish translations. Please walk us through changes.

@MocanaAtBroad Are we good to go?

**Review by ssettipalli — APPROVED** [review]
looks good to me

**Pull request merged**
