### PR TITLE
pex: first-class support for values and comparison

### PR DESCRIPTION
**Pull request by yufengwng**
## Context

These are the core changes to transform PEX into a more flexible and powerful expression language.

**These changes are backwards-compatible.**
* This PR rewrote the grammar rules and updated the interpreter implementation, but it results in mostly the same semantics and the syntax of all existing PEX in the wild are still valid.
* With this, we can now write syntax that we were not able to before, like proper comparisons!
* This will also enable us to more easily build features we'll need soon.

_It might look like a lot of changes, but a good amount is just moving/reordering/consolidating code._

## Checklist

- [x] I have labeled the type of changes involved using the `C-*` labels.
- [x] I have assessed potential risks and labeled using the `R-*` labels.
- [x] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x] I have considered security and privacy, and added `I-*` labels as needed
- [x] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.

## FUD Score

_Overall, how are you feeling about these changes?_

- [x] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [x] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [x] I have written automated positive tests
- [x] I have written automated negative tests
- [x] I have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [x] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

### CODE REVIEW

**Comment by yufengwng** [comment]
please run tests

**Comment by yufengwng** [comment]
please run tests

**Comment by yufengwng** [comment]
please run tests

**Review by raiks2 — APPROVED** [review]
LGTM

**Pull request merged**
